[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["blocking", "rustls-tls"] }
dotenv = "0.15.0"
